fail_fast: true
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: make import-sort
        language: system
        types: [python]

      - id: fmt
        name: fmt
        entry: make fmt
        language: system
        types: [python]

      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [python]

      - id: type-check
        name: type-check
        entry: make type-check
        language: system
        types: [python]
